OBSatstaSSf <- function(sta){
  # The objective of this function is to extract data from a global frame ( generated by the "...Load.R" function ) for a given station (argument sta)
  

  
  # If we agree on Conventions we should be able to bypass those lines
  colnames(datadfpr)[which(colnames(datadfpr)=="OC")]<-"TOC"
  colnames(datadfpr)[which(colnames(datadfpr)=="ON")]<-"TN"
  colnames(datadfpr)[which(colnames(datadfpr)=="SiO2")]<-"SIO"
  colnames(datadfpr)[which(colnames(datadfpr)=="Bsi")]<-"SiDet"
  colnames(datadfpr)[which(colnames(datadfpr)=="TCO2")]<-"DIC"
  
  ##Add variables
  datadfpr<-ddply(datadfpr,.(Station), function(dsub){
    print(dsub)
    Surnind<-which(dsub[,"MidDepth"]==0)
    print(Surnind)
    DICdelt <- dsub[,"DIC"]-dsub[Surnind,"DIC"]
    DINdelt <- dsub[,"NH3"]-dsub[Surnind,"NH3"]
    DIPdelt <- dsub[,"PO4"]-dsub[Surnind,"PO4"]
    cbind(dsub, data.frame( 
                            DICdelt = DICdelt,
                            DINdelt = DINdelt,
                            DIPdelt = DIPdelt,
                            CN = DICdelt/DINdelt,
                            CP = DICdelt/DIPdelt,
                            NP = DINdelt/DIPdelt)
    )
  }
  )
  
  # remove data above SWI  
  bTM <-subset(datadfpr,MidDepth>0 & Station==sta,select=c("MidDepth","UpperDepth","LowerDepth",varlimod))

  b1<-melt(bTM,.(MidDepth,UpperDepth,LowerDepth))

  # what is called time here is a depth index  .. we should change this
  b1$time<-seq(1:length(bTM[,1]))
  
#   Analyses of chamber waters and pore waters were
#   carried out using techniques cited in Giordani and
#   Hammond 1985. 
#   Analytical precisions (+-1 \sigma) based on replicates are: 
  # silica 4 %
  # ammonia 0.4 µM or 4%.,
  # nitrate 0.8 mM or 4%.,
  # phosphate 0.10 mM or 4 %
  # Oxygen 4%. was measured colorimetrically,
# as described in Berelson et al. Ž1990.. Radon Ž5%.

  # Is error present in the datafile ? 
#  b1[which(b1$var=="DIC"),"err"]  <- datadfpr$DIC_ERR[which(datadfpr$MidDepth>0 & datadfpr$Station==sta )]
#  b1[which(b1$var=="PO4"),"err"]  <- datadfpr$PO4_ERR[which(datadfpr$MidDepth>0 & datadfpr$Station==sta )]
#  b1[which(b1$var=="SIO"),"err"]  <- datadfpr$SIO_ERR[which(datadfpr$MidDepth>0 & datadfpr$Station==sta )]
#  b1[which(b1$var=="NH3"),"err"]  <- datadfpr$NH3_ERR[which(datadfpr$MidDepth>0 & datadfpr$Station==sta )]
#  b1[which(b1$var=="TOC"),"err"]  <- datadfpr$TOC_ERR[which(datadfpr$MidDepth>0 & datadfpr$Station==sta )]
#  b1[which(b1$var=="TN"),"err"]  <- datadfpr$TN_ERR[which(datadfpr$MidDepth>0 & datadfpr$Station==sta )]
#  b1[which(b1$var=="SiDet"),"err"]  <- datadfpr$SiDet_ERR[which(datadfpr$MidDepth>0 & datadfpr$Station==sta )]
  
  # Or should it be provided as a relative value (the case here) 
  b1[which(b1$var=="DIC"),"err"]  <- b1[which(b1$var=="DIC"),"value"]*0.04
  b1[which(b1$var=="PO4"),"err"]  <- max( b1[which(b1$var=="PO4"),"value"]*0.04, 0.1  )
  b1[which(b1$var=="SIO"),"err"]  <- b1[which(b1$var=="SIO"),"value"]*0.04
    b1[which(b1$var=="NH3"),"err"]  <- max( b1[which(b1$var=="NH3"),"value"]*0.04, 0.4  )
  b1[which(b1$var=="TOC"),"err"]  <- b1[which(b1$var=="TOC"),"value"]*0.02
  b1[which(b1$var=="TN"),"err"]  <- b1[which(b1$var=="TN"),"value"]*0.07
 b1[which(b1$var=="SiDet"),"err"]<- b1[which(b1$var=="SiDet"),"value"]*0.02*5
  
  b1<-b1[,c("variable","time","value","err","LowerDepth","UpperDepth" )]
  
  
  # Original data are contained in "datadfprfl"
  bO2f<-data.frame(variable="O2flux",
                   time=length(bTM[,1])+1,
                   value=-datadffl[which(datadffl$Station==sta),"FO2"],
                   err=min(datadffl[which(datadffl$Station==sta),"FO2_ERR"],1.5),
                   LowerDepth=0,
                   UpperDepth=0
                   )
  bDICf<-data.frame(variable="DICflux",
                   time=length(bTM[,1])+1,
                   value=-datadffl[which(datadffl$Station==sta),"FDIC"],
                   err=datadffl[which(datadffl$Station==sta),"FDIC_ERR"],
                   LowerDepth=0,
                   UpperDepth=0
  )
  bNO3f<-data.frame(variable="NO3flux",
                   time=length(bTM[,1])+1,
                   value=-datadffl[which(datadffl$Station==sta),"FNO3"],
                   err=datadffl[which(datadffl$Station==sta),"FNO3_ERR"],
                   LowerDepth=0,
                   UpperDepth=0
  )
  bNH3f<-data.frame(variable="NH3flux",
                   time=length(bTM[,1])+1,
                   value=-datadffl[which(datadffl$Station==sta),"FNH3"],
                   err=datadffl[which(datadffl$Station==sta),"FNH3_ERR"],
                   LowerDepth=0,
                   UpperDepth=0
  )
  bSIOf<-data.frame(variable="SIOflux",
                   time=length(bTM[,1])+1,
                   value=-datadffl[which(datadffl$Station==sta),"FSIO"],
                   err=datadffl[which(datadffl$Station==sta),"FSIO_ERR"],
                   LowerDepth=0,
                   UpperDepth=0
  )
  bPO4f<-data.frame(variable="PO4flux",
                    time=length(bTM[,1])+1,
                    value=-datadffl[which(datadffl$Station==sta),"FPO4"],
                    err=datadffl[which(datadffl$Station==sta),"FPO4_ERR"],
                    LowerDepth=0,
                    UpperDepth=0
  )
  
  # Impose common error on fluxes, taken from the median of estimated errors 
  if (F) {
     bO2f["err"] <-4.5
    bDICf["err"] <-3.8
    bNO3f["err"] <-0.12
    bNH3f["err"] <-0.38
    bSIOf["err"] <-0.5
    bPO4f["err"] <-0.03
  }
  
  b1<-rbind(b1,bO2f,bDICf,bNO3f,bNH3f,bSIOf,bPO4f)
  
return(b1)
}
