OBSatstaSSf <- function(sta,cam){
  # The objective of this function is to extract data from a global frame ( generated by the "...Load.R" function ) for a given station (argument sta)

  ##Prepare nutrient data
  # remove data above SWI  
  bTM <-subset(datadfpr,MidDepth>0 & Station==sta & Campaign==cam,select=c("MidDepth","UpperDepth","LowerDepth",varlimod))

  bTP <-subset(datadfpo,MidDepth>0 & Station==sta,select=c("MidDepth","UpperDepth","LowerDepth",varlimodpo))

  b1<-melt(bTM,.(MidDepth,UpperDepth,LowerDepth))
  
  #b2<-melt(bTP,.(MidDepth,UpperDepth,LowerDepth))

  #b1<-rbind(b1,b2)
    # what is called time here is a depth index  .. we should change this
  b1$time<-seq(1:length(bTM[,1]))
  
#   Analyses of chamber waters and pore waters were
#   carried out using techniques cited in Giordani and
#   Hammond 1985. 
#   Analytical precisions (+-1 \sigma) based on replicates are: 
  # silica 4 %
  # ammonia 0.4 µM or 4%.,
  # nitrate 0.8 mM or 4%.,
  # phosphate 0.10 mM or 4 %
  # Oxygen 4%. was measured colorimetrically,
# as described in Berelson et al. Ž1990.. Radon Ž5%.

  # A.Eisele 23.10.1017: reading error present in datafile
  b1[which(b1$var=="PO4"),"err"]  <- datadfpr$PO4_ERR[which(datadfpr$MidDepth>0 & datadfpr$Station==sta & datadfpr$Campaign==cam)]
  b1[which(b1$var=="SIO"),"err"]  <- datadfpr$SIO_ERR[which(datadfpr$MidDepth>0 & datadfpr$Station==sta & datadfpr$Campaign==cam)]
  b1[which(b1$var=="NH3"),"err"]  <- datadfpr$NH3_ERR[which(datadfpr$MidDepth>0 & datadfpr$Station==sta & datadfpr$Campaign==cam)] 
  b1[which(b1$var=="NO3"),"err"]  <- datadfpr$NO3_ERR[which(datadfpr$MidDepth>0 & datadfpr$Station==sta & datadfpr$Campaign==cam)] 

#  b1[which(b1$var=="NP"),"err"]  <- datadfpo$NP_ERR[which(datadfpo$MidDepth>0 & datadfpo$Station==sta)]
#  b1[which(b1$var=="CN"),"err"]  <- datadfpo$CN_ERR[which(datadfpo$MidDepth>0 & datadfpo$Station==sta)] 
 # b1[which(b1$var=="CP"),"err"]  <- datadfpo$CP_ERR[which(datadfpo$MidDepth>0 & datadfpo$Station==sta)] 
  

  ### TODO: adding an automatical checkup if the error is available in the original data and if not progessing with the following assumptions...
  
  # Or should it be provided as a relative value (the case here) 
 # b1[which(b1$var=="DIC"),"err"]  <- b1[which(b1$var=="DIC"),"value"]*0.04
 # b1[which(b1$var=="PO4"),"err"]  <- b1[which(b1$var=="PO4"),"value"]*0.04
#  b1[which(b1$var=="SIO"),"err"]  <- b1[which(b1$var=="SIO"),"value"]*0.04
#  b1[which(b1$var=="NH3"),"err"]  <- b1[which(b1$var=="NH3"),"value"]*0.04  
 # b1[which(b1$var=="TOC"),"err"]  <- b1[which(b1$var=="TOC"),"value"]*0.02
#  b1[which(b1$var=="TN"),"err"]  <- b1[which(b1$var=="TN"),"value"]*0.07
#  b1[which(b1$var=="SiDet"),"err"]<- b1[which(b1$var=="SiDet"),"value"]*0.02*5
  
  
  
  b1<-b1[,c("variable","time","value","err","LowerDepth","UpperDepth" )]
  
  
  # Original data are contained in "datadffl"
  bO2f<-data.frame(variable="O2flux",
                   time=length(bTM[,1])+1,
                   value=-datadffl[which(datadffl$Station==sta & datadffl$Campaign==cam),"FO2"],
                  err=min(datadffl[which(datadffl$Station==sta & datadffl$Campaign==cam),"FO2_ERR"],1.5),
                   LowerDepth=0,
                   UpperDepth=0
                   )
#  bDICf<-data.frame(variable="DICflux",
 #                  time=length(b1[,1])+1,
  #                 value=-datadffl[which(datadffl$Station==sta),"FDIC"],
   #                err=datadffl[which(datadffl$Station==sta),"FDIC_ERR"],
    #               LowerDepth=0,
     #              UpperDepth=0
  #)
  bNO3f<-data.frame(variable="NO3flux",
                   time=length(bTM[,1])+1,
                   value=-datadffl[which(datadffl$Station==sta) & datadffl$Campaign==cam,"FNO3"],
                   err=datadffl[which(datadffl$Station==sta & datadffl$Campaign==cam),"FNO3_ERR"],
                   LowerDepth=0,
                   UpperDepth=0
  )
  bNH3f<-data.frame(variable="NH3flux",
                   time=length(bTM[,1])+1,
                   value=-datadffl[which(datadffl$Station==sta & datadffl$Campaign==cam),"FNH3"],
                   err=datadffl[which(datadffl$Station==sta & datadffl$Campaign==cam),"FNH3_ERR"],
                   LowerDepth=0,
                   UpperDepth=0
  )
  bSIOf<-data.frame(variable="SIOflux",
                   time=length(bTM[,1])+1,
                   value=-datadffl[which(datadffl$Station==sta & datadffl$Campaign==cam),"FSIO"],
                   err=datadffl[which(datadffl$Station==sta & datadffl$Campaign==cam),"FSIO_ERR"],
                   LowerDepth=0,
                   UpperDepth=0
  )
  bPO4f<-data.frame(variable="PO4flux",
                    time=length(bTM[,1])+1,
                    value=-datadffl[which(datadffl$Station==sta & datadffl$Campaign==cam),"FPO4"],
                    err=datadffl[which(datadffl$Station==sta & datadffl$Campaign==cam),"FPO4_ERR"],
                    LowerDepth=0,
                    UpperDepth=0
  )
  CN<-data.frame(variable="CN",
                    time=length(b1[,1])+1,
                    value=-mean(datadfpo[which(datadfpo$Station==sta),"CN"]),
                    err=mean(datadfpo[which(datadfpo$Station==sta),"CN_ERR"]),
                    LowerDepth=0,
                    UpperDepth=0
  )
  
  CP<-data.frame(variable="CP",
                 time=length(b1[,1])+1,
                 value=-mean(datadfpo[which(datadfpo$Station==sta),"CP"]),
                 err=mean(datadfpo[which(datadfpo$Station==sta),"CP_ERR"]),
                 LowerDepth=0,
                 UpperDepth=0
  )
  NP<-data.frame(variable="NP",
                 time=length(b1[,1])+1,
                 value=-mean(datadfpo[which(datadfpo$Station==sta),"NP"]),
                 err=mean(datadfpo[which(datadfpo$Station==sta),"NP_ERR"]),
                 LowerDepth=0,
                 UpperDepth=0
  )
  
  
  # bTP <-subset(datadfpo,MidDepth>0 & Station==sta,select=c("MidDepth","UpperDepth","LowerDepth",varlimodpo))
  
  # Impose common error on fluxes, taken from the median of estimated errors 
  if (F) {
     bO2f["err"] <-4.5
    bDICf["err"] <-3.8
    bNO3f["err"] <-0.12
    bNH3f["err"] <-0.38
    bSIOf["err"] <-0.5
    bPO4f["err"] <-0.03
  }
  
  b1<-rbind(b1,bNO3f,bNH3f,bSIOf,bPO4f,bO2f,CN) #bDICf NP CP
  
return(b1)
}
